-- Tablas del esquema público

create table public.fechas_Q (
  id text primary key default ''::text,
  inicio date,
  final date
);

create table public.horarios (
  id integer generated by default as identity primary key,
  horario text unique not null
);

create table public.incidentes (
  id bigint generated always as identity primary key,
  laboratorio_id text not null,
  laboratorio_nombre text not null,
  descripcion text not null,
  usuario_email text not null,
  reporte_link text,
  fecha_hora timestamptz default now()
);

create table public.laboratorios (
  id integer generated by default as identity primary key,
  nombre text unique not null
);

create table public.usuarios (
  id integer generated by default as identity primary key,
  nombre text not null,
  numero_cuenta text not null,
  correo text not null,
  tipo_usuario text not null,
  constraint usuarios_tipo_usuario_check check (
    tipo_usuario = any (array[
      'Estudiante'::text,
      'Docente'::text,
      'Administrativo'::text,
      'Prospección'::text,
      'Educación Continua'::text
    ])
  )
);

create table public.reservaciones (
  id integer generated by default as identity primary key,
  motivo_uso text not null,
  cantidad_usuarios integer not null check (cantidad_usuarios > 0),
  fecha date not null,
  dias_repeticion text,
  laboratorio_id integer not null references public.laboratorios(id),
  grupo_id uuid,
  estado text default 'EN_ESPERA'::text,
  descripcion text
);

create table public.reservaciones_horarios (
  id integer generated by default as identity primary key,
  reservacion_id integer not null references public.reservaciones(id),
  horario_id integer not null references public.horarios(id)
);

create table public.reservaciones_usuarios (
  id integer generated by default as identity primary key,
  reservacion_id integer not null references public.reservaciones(id),
  usuario_id integer not null references public.usuarios(id)
);

-- Políticas RLS (idénticas a producción)

alter table public.reservaciones enable row level security;

create policy "Todos pueden insertar" on public.reservaciones
  for insert with check (true);

create policy "Insertar_Reservaciones" on public.reservaciones
  for insert with check (true);

create policy "Leer_Reservaciones" on public.reservaciones
  for select using (true);

create policy "Editar_Reservaciones" on public.reservaciones
  for delete using (auth.email() = 'winder.matamoros@unitec.edu.hn'::text);

-- Datos semilla

insert into public.horarios (horario) values
  ('6:45 AM - 8:10 AM'),
  ('8:10 AM - 9:30 AM'),
  ('9:55 AM - 11:15 AM'),
  ('11:15 AM - 12:35 PM'),
  ('12:35 PM - 1:20 PM'),
  ('1:20 PM - 2:40 PM'),
  ('2:40 PM - 4:00 PM'),
  ('4:00 PM - 5:20 PM'),
  ('5:20 PM - 6:40 PM'),
  ('6:40 PM - 8:00 PM'),
  ('8:00 PM - 9:20 PM');

insert into public.laboratorios (nombre) values
  ('Laboratorio de Computo 1'),
  ('Laboratorio de Computo 2'),
  ('Laboratorio de Computo 3'),
  ('Laboratorio de Redes'),
  ('Laboratorio de Electrónica');

-- Permisos para las API roles (cuando auto_expose_new_tables esté deshabilitado)

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on all tables in schema public to anon, authenticated;
grant usage on all sequences in schema public to anon, authenticated;
